### ISSUE TITLE
Ping backdoor

### ISSUE THREAD

**Issue by PizzaWhisperer** [xavierpantet/my_ass_on_your_grass#12] opened 2019-05-16 13:29 UTC
After running `make`, launch the server with `./bin/server`.

Then launch the client with `./bin/client 127.0.0.1 1337` and feed it with 
```
ping pong
```
which pops a calc on the server side.
Indeed at the lines https://github.com/xavierpantet/my_ass_on_your_grass/blob/5ebeb6c98d689621444de3275847f134462da9b7/src/commands/Commands.cpp#L399-L400 the user input is compared to "pong" and a calc pops if equal.

**Comment by xavierpantet** [comment] 2019-05-16 14:27
Duplicate of #1

**Closed as completed by xavierpantet** 2019-05-16 14:27 UTC
Labels: duplicate
